/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CustomerAnalyticsRouteImport } from './routes/customer-analytics'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LiveStoreRouteImport } from './routes/live-store'
import { Route as QueueMonitoringRouteImport } from './routes/queue-monitoring'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAnalyticsRoute = CustomerAnalyticsRouteImport.update({
  id: '/customer-analytics',
  path: '/customer-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStoreRoute = LiveStoreRouteImport.update({
  id: '/live-store',
  path: '/live-store',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueMonitoringRoute = QueueMonitoringRouteImport.update({
  id: '/queue-monitoring',
  path: '/queue-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/billing': typeof BillingRoute
  '/customer-analytics': typeof CustomerAnalyticsRoute
  '/inventory': typeof InventoryRoute
  '/live-store': typeof LiveStoreRoute
  '/queue-monitoring': typeof QueueMonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/billing': typeof BillingRoute
  '/customer-analytics': typeof CustomerAnalyticsRoute
  '/inventory': typeof InventoryRoute
  '/live-store': typeof LiveStoreRoute
  '/queue-monitoring': typeof QueueMonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/billing': typeof BillingRoute
  '/customer-analytics': typeof CustomerAnalyticsRoute
  '/inventory': typeof InventoryRoute
  '/live-store': typeof LiveStoreRoute
  '/queue-monitoring': typeof QueueMonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/billing'
    | '/customer-analytics'
    | '/inventory'
    | '/live-store'
    | '/queue-monitoring'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/billing'
    | '/customer-analytics'
    | '/inventory'
    | '/live-store'
    | '/queue-monitoring'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/billing'
    | '/customer-analytics'
    | '/inventory'
    | '/live-store'
    | '/queue-monitoring'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  BillingRoute: typeof BillingRoute
  CustomerAnalyticsRoute: typeof CustomerAnalyticsRoute
  InventoryRoute: typeof InventoryRoute
  LiveStoreRoute: typeof LiveStoreRoute
  QueueMonitoringRoute: typeof QueueMonitoringRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-analytics': {
      id: '/customer-analytics'
      path: '/customer-analytics'
      fullPath: '/customer-analytics'
      preLoaderRoute: typeof CustomerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-store': {
      id: '/live-store'
      path: '/live-store'
      fullPath: '/live-store'
      preLoaderRoute: typeof LiveStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-monitoring': {
      id: '/queue-monitoring'
      path: '/queue-monitoring'
      fullPath: '/queue-monitoring'
      preLoaderRoute: typeof QueueMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  BillingRoute: BillingRoute,
  CustomerAnalyticsRoute: CustomerAnalyticsRoute,
  InventoryRoute: InventoryRoute,
  LiveStoreRoute: LiveStoreRoute,
  QueueMonitoringRoute: QueueMonitoringRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
